name: Build {{cookiecutter.name}}
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    # if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: Setup Java 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          cache: gradle
          java-version: 21

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        
      - name: Clean Build
        run: ./gradlew build --no-daemon -x test --warning-mode all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}