name: Update cookiecutter.json and Trigger Setup Workflow

on:
  issue_comment:
    types: [created]  # Triggered when a new comment is added to an issue

jobs:
  if: ${{ github.event.issue.number == 1 }}  # Only run if the issue number is 1 (first issue)
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get issue comment body
        id: comment
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"

      - name: Parse the comment and update cookiecutter.json
        id: update_json
        run: |
          # Extract the comment body
          comment="${{ github.event.comment.body }}"

          # Parse variables from the comment
          name=$(echo "$comment" | grep -oP 'name:\s*\K.*')
          version=$(echo "$comment" | grep -oP 'version:\s*\K.*')
          group=$(echo "$comment" | grep -oP 'group:\s*\K.*')
          authors=$(echo "$comment" | grep -oP 'authors:\s*\K.*')
          description=$(echo "$comment" | grep -oP 'description:\s*\K.*')
          apiversion=$(echo "$comment" | grep -oP 'apiversion:\s*\K.*')
          minecraft=$(echo "$comment" | grep -oP 'minecraft:\s*\K.*')
          depend=$(echo "$comment" | grep -oP 'depend:\s*\K.*')
          softdepend=$(echo "$comment" | grep -oP 'softdepend:\s*\K.*')

          # Split group into pack_tld, pack_name, and pack_plugin
          IFS='.' read -r pack_tld pack_name pack_plugin <<< "$group"

          # Update cookiecutter.json with the extracted values
          jq --arg name "$name" \
             --arg version "$version" \
             --arg group "$group" \
             --arg authors "$authors" \
             --arg description "$description" \
             --arg apiversion "$apiversion" \
             --arg minecraft "$minecraft" \
             --arg depend "$depend" \
             --arg softdepend "$softdepend" \
             --arg pack_tld "$pack_tld" \
             --arg pack_name "$pack_name" \
             --arg pack_plugin "$pack_plugin" \
             '.name = $name |
              .version = $version |
              .group = $group |
              .authors = $authors |
              .description = $description |
              .apiversion = $apiversion |
              .minecraft = $minecraft |
              .depend = $depend |
              .softdepend = $softdepend |
              .pack_tld = $pack_tld |
              .pack_name = $pack_name |
              .pack_plugin = $pack_plugin' \
             cookiecutter.json > tmp.json && mv tmp.json cookiecutter.json

      - name: Commit the changes to cookiecutter.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cookiecutter.json
          git commit -m "Update cookiecutter.json with user input"
          git push
  
  trigger_setup_workflow:
    needs: update_json
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Setup Workflow
        run: |
          # Trigger another workflow (e.g., setup workflow) after cookiecutter.json update
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "start-setup-workflow"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
